# Generated by Django 2.2.24 on 2022-04-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='platformLocality',
        ),
    ]
