# Generated by Django 2.2.24 on 2022-06-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_remove_platform_platformlocality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='platform',
            name='geographicExtend',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('MACRORREGIONAL', 'Macrorregional'), ('NACIONAL', 'Nacional'), ('REGIONAL', 'Regional'), ('MUNICIPAL', 'Municipal'), ('VIZINHANÇA', 'Vizinhança')], max_length=15),
        ),
        migrations.AddField(
            model_name='platform',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='platforms.Keyword'),
        ),
    ]
