# Generated by Django 2.2.24 on 2022-07-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_auto_20220607_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
    ]
