# Generated by Django 2.2.24 on 2022-07-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_auto_20220706_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(sql="UPDATE platforms_platform SET active = TRUE;"),
    ]
