# Generated by Django 2.2.24 on 2022-07-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_platform_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='organisation',
            field=models.ManyToManyField(blank=True, to='organisations.Organisation'),
        ),
    ]
