# Generated by Django 2.2.28 on 2023-06-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_auto_20230607_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='geoExtend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platforms.GeographicExtend'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='geographicExtend',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('MACRORREGIONAL', 'Macrorregional'), ('NACIONAL', 'Nacional'), ('REGIONAL', 'Regional'), ('MUNICIPAL', 'Municipal'), ('VIZINHANÇA', 'Vizinhança')], max_length=15, null=True),
        ),
    ]
