# Generated by Django 3.2.21 on 2023-10-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_auto_20230608_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geographicextend',
            options={'verbose_name': 'Geographic extent', 'verbose_name_plural': 'Geographic extents'},
        ),
    ]
