# Generated by Django 3.2.25 on 2026-05-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('ICD', models.CharField(blank=True, max_length=5, null=True, verbose_name='ICD')),
                ('other_names', models.TextField(blank=True, null=True, verbose_name='Other names')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('symptoms', models.ManyToManyField(blank=True, to='diseases.Symptom')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['name'],
            },
        ),
    ]
