# Generated by Django 3.2.25 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='diseases.Symptom', verbose_name='Symptoms'),
        ),
    ]
