# Generated by Django 3.2.23 on 2024-05-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eucs_platform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
