# Generated by Django 3.2.25 on 2026-06-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('header', models.TextField(blank=True, null=True, verbose_name='Header')),
                ('content', models.TextField(verbose_name='Content')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish'), ('en', 'English')], max_length=5, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('header', models.TextField(blank=True, null=True, verbose_name='Header')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish'), ('en', 'English')], max_length=5, verbose_name='Language')),
                ('explain', models.TextField(blank=True, null=True, verbose_name='Documentation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('header', models.TextField(blank=True, null=True, verbose_name='Header')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('language', models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish'), ('en', 'English')], max_length=5, verbose_name='Language')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='pages.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('slug', 'language'), name='unique_page_slug_language'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='pages.section', verbose_name='Section'),
        ),
    ]
