# Generated by Django 2.2.24 on 2023-03-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_auto_20200717_1026'),
        ('resources', '0052_auto_20230323_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('headline', models.TextField(verbose_name='Headline')),
                ('featured_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Featured Title')),
                ('featured_text', models.TextField(blank=True, null=True, verbose_name='Featured Text')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Source HTML')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('R', 'Ready'), ('Q', 'Queued'), ('S', 'Sent'), ('E', 'Error')], default='D', max_length=1, verbose_name='Status')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Post')),
                ('featured_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('opt_out', models.BooleanField(default=False)),
                ('last_newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Newsletter')),
            ],
        ),
    ]
