# Generated by Django 2.2.24 on 2023-03-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20230324_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-id',), 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='read_count',
            field=models.BigIntegerField(default=0, verbose_name='Read Count'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='sent_count',
            field=models.BigIntegerField(default=0, verbose_name='Sent Count'),
        ),
    ]
