# Generated by Django 2.2.24 on 2023-04-05 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20230328_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-id',), 'verbose_name': 'Subscriber'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='organisation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='featured_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Resource', verbose_name='Feature Resource'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='Valid Email'),
        ),
    ]
