# Generated by Django 3.2.21 on 2023-10-09 12:52

import contact.models
from django.db import migrations, models
import machina.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20230904_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumproposal',
            options={'verbose_name': 'Forum Proposal', 'verbose_name_plural': 'Forum Proposals'},
        ),
        migrations.RemoveField(
            model_name='forumproposal',
            name='_description_rendered',
        ),
        migrations.AlterField(
            model_name='forumproposal',
            name='approved',
            field=models.NullBooleanField(verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='forumproposal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='forumproposal',
            name='image',
            field=machina.models.fields.ExtendedImageField(blank=True, null=True, upload_to=contact.models.forum_proposal_upload_to, verbose_name='Forum image'),
        ),
    ]
