# Generated by Django 3.2.21 on 2023-10-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20231009_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumproposal',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Approved'),
        ),
    ]
