# Generated by Django 3.2.25 on 2025-01-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_forumproposal_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumProposal',
        ),
    ]
