# Generated by Django 2.2.24 on 2022-04-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20220405_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='aim',
        ),
    ]
