# Generated by Django 2.2.24 on 2022-06-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_remove_project_aim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='geographicextend',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectlocality',
        ),
        migrations.DeleteModel(
            name='GeographicExtend',
        ),
    ]
