# Generated by Django 2.2.24 on 2022-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20220607_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organisation',
            field=models.ManyToManyField(blank=True, to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participationTask',
            field=models.ManyToManyField(blank=True, to='projects.ParticipationTask'),
        ),
    ]
