# Generated by Django 2.2.24 on 2022-11-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20220916_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationtask',
            options={'ordering': ['participationTask'], 'verbose_name': 'Participation Task', 'verbose_name_plural': 'Participation Task'},
        ),
    ]
