# Generated by Django 2.2.24 on 2022-11-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20220916_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unapprovedprojects',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='moderated',
        ),
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='ApprovedProjects',
        ),
        migrations.DeleteModel(
            name='UnApprovedProjects',
        ),
    ]
