# Generated by Django 2.2.24 on 2022-11-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_auto_20221103_1137'),
        ('projects', '0066_auto_20221102_2117'),
    ]

    operations = [
    ]
