# Generated by Django 2.2.28 on 2023-01-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_auto_20221129_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpermission',
            options={'verbose_name': 'Project Permission', 'verbose_name_plural': 'Project Permissions'},
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='originURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
