# Generated by Django 2.2.24 on 2022-11-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20221105_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Project Status', 'verbose_name_plural': 'Project Status'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic'},
        ),
        migrations.AlterField(
            model_name='project',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='project',
            name='originURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.ManyToManyField(to='projects.Topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.TextField(verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.TextField(verbose_name='Topic'),
        ),
    ]
