# Generated by Django 2.2.24 on 2023-03-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_auto_20230122_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingbody',
            options={'ordering': ['body'], 'verbose_name': 'Funding Body'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['keyword'], 'verbose_name': 'Keyword'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('status',), 'verbose_name': 'Project Status', 'verbose_name_plural': 'Project Status'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topic'], 'verbose_name': 'Topic'},
        ),
        migrations.AlterModelOptions(
            name='translatedproject',
            options={'ordering': ['translatedDescription'], 'verbose_name': 'Translated Project'},
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Invite Accepted'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cooperator'),
        ),
    ]
