# Generated by Django 3.2.21 on 2023-10-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_auto_20230323_1545'),
        ('projects', '0071_topic_external_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingbody',
            options={'ordering': ['body'], 'verbose_name': 'Funding Body', 'verbose_name_plural': 'Funding Body'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['keyword'], 'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterField(
            model_name='project',
            name='mainOrganisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_organisation', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.ManyToManyField(blank=True, to='projects.Topic', verbose_name='Topic'),
        ),
    ]
