# Generated by Django 3.2.23 on 2024-05-12 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0072_auto_20231009_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermission',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Invite accepted'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Editor'),
        ),
    ]
