# Generated by Django 2.2.28 on 2023-02-03 19:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('task_module', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=100)),
                ('task_kwargs', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
    ]
