# Generated by Django 3.2.21 on 2023-10-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtask',
            name='task_kwargs',
            field=models.JSONField(verbose_name='Task Params'),
        ),
    ]
