# Generated by Django 3.2.23 on 2024-05-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_activationtask_task_kwargs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtask',
            name='task_kwargs',
            field=models.JSONField(verbose_name='Task Parameters'),
        ),
    ]
