# Generated by Django 2.2.24 on 2022-11-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20221129_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Approved'),
        ),
    ]
