# Generated by Django 2.2.24 on 2023-03-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20221129_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unapprovedevents',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Event'},
        ),
        migrations.DeleteModel(
            name='ApprovedEvents',
        ),
        migrations.DeleteModel(
            name='UnApprovedEvents',
        ),
    ]
