# Generated by Django 3.2.21 on 2023-10-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20211125_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestarea',
            options={'verbose_name': 'Interest Area', 'verbose_name_plural': 'Interest Areas'},
        ),
    ]
