# Generated by Django 3.2.23 on 2024-05-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_interestarea_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID (If you have registered on the ORCID platform for researchers, you may add your persistent digital identifier, or ORCID iD, to link this profile with your professional information such as affiliations, grants, publications, peer review, and more.)'),
        ),
    ]
