# Generated by Django 3.2.25 on 2025-09-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_profile_orcid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='digest',
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Team'),
        ),
    ]
