# Generated by Django 2.2.24 on 2022-04-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0045_auto_20211026_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='conditionsOfAccess',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='educationLevel',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='learningResourceType',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='timeRequired',
        ),
        migrations.DeleteModel(
            name='EducationLevel',
        ),
        migrations.DeleteModel(
            name='LearningResourceType',
        ),
    ]
