# Generated by Django 2.2.24 on 2022-07-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0047_auto_20220607_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='authors',
            field=models.ManyToManyField(blank=True, to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='organisation',
            field=models.ManyToManyField(blank=True, to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='theme',
            field=models.ManyToManyField(blank=True, to='resources.Theme'),
        ),
    ]
