# Generated by Django 2.2.24 on 2022-09-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0048_auto_20220727_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audience',
            options={'verbose_name': 'Audience'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Category'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='theme',
            field=models.ManyToManyField(to='resources.Theme'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='isTrainingResource',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Training Resource'),
        ),
    ]
