# Generated by Django 2.2.24 on 2022-11-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0050_auto_20221123_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='moderated',
        ),
        migrations.AlterField(
            model_name='resource',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Approved'),
        ),
    ]
