# Generated by Django 2.2.24 on 2023-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0051_auto_20221129_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unapprovedresources',
            name='resource',
        ),
        migrations.AlterModelOptions(
            name='audience',
            options={'ordering': ['audience'], 'verbose_name': 'Audience', 'verbose_name_plural': 'Audiences'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Resource Category', 'verbose_name_plural': 'Resource Categories'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['keyword'], 'verbose_name': 'Resource Keyword', 'verbose_name_plural': 'Resource Keywords'},
        ),
        migrations.AlterModelOptions(
            name='resourcegroup',
            options={'ordering': ['name'], 'verbose_name': 'Resource Group', 'verbose_name_plural': 'Resource Groups'},
        ),
        migrations.AlterModelOptions(
            name='resourcesgrouped',
            options={'verbose_name': 'Resources Grouped'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['theme'], 'verbose_name': 'Theme'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='datePublished',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year published'),
        ),
        migrations.DeleteModel(
            name='ApprovedResources',
        ),
        migrations.DeleteModel(
            name='UnApprovedResources',
        ),
    ]
