# Generated by Django 3.2.23 on 2024-05-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0052_auto_20230323_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Resource category', 'verbose_name_plural': 'Resource categories'},
        ),
    ]
