# Generated by Django 3.2.25 on 2026-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0053_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dateUploaded',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description_citizen_science_aspects',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='imageCredit2',
        ),
        migrations.AlterField(
            model_name='resource',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='inLanguage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
    ]
