# Generated by Django 3.2.25 on 2025-01-24 18:24

from django.db import migrations, models
import django.db.models.deletion


def load_index_type(apps, schema_editor):
    from utilities.models import SearchIndexType

    db_alias = schema_editor.connection.alias

    IndexType = apps.get_model("utilities", "IndexType")

    IndexType.objects.using(db_alias).create(type=SearchIndexType.PROJECT.value, order=1)
    IndexType.objects.using(db_alias).create(type=SearchIndexType.PLATFORM.value, order=2)
    IndexType.objects.using(db_alias).create(type=SearchIndexType.RESOURCE.value, order=3)
    IndexType.objects.using(db_alias).create(type=SearchIndexType.TRAINING.value, order=4)
    IndexType.objects.using(db_alias).create(type=SearchIndexType.ORGANISATION.value, order=5)
    IndexType.objects.using(db_alias).create(type=SearchIndexType.PROFILE.value, order=6)
    IndexType.objects.using(db_alias).create(type=SearchIndexType.EVENT.value, order=7)


class Migration(migrations.Migration):
    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[('project', 'Projects'), ('resource', 'Resources'), ('training', 'Training Resources'),
                             ('organisation', 'Organisations'), ('platform', 'Platforms'), ('profile', 'Users'),
                             ('event', 'Events')], max_length=20, unique=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Search Index Type',
                'verbose_name_plural': 'Search Index Types',
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=40)),
                ('object_repr', models.CharField(max_length=255)),
                ('language',
                 models.CharField(choices=[('pt-br', 'Brazilian Portuguese'), ('es', 'Spanish'), ('en', 'English')],
                                  default='pt-br', max_length=5, verbose_name='Language')),
                ('text', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('type', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT,
                                           to='utilities.indextype')),
            ],
            options={
                'verbose_name': 'Search Index',
                'verbose_name_plural': 'Search Indexes',
                'db_table': 'search',
                'unique_together': {('type', 'object_id', 'language')},
            },
        ),
        migrations.RunPython(load_index_type),
    ]
