# Generated by Django 2.2.24 on 2022-08-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_auto_20211026_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'verbose_name': 'Organization Type', 'verbose_name_plural': 'Organization Types'},
        ),
    ]
