# Generated by Django 2.2.24 on 2022-09-22 19:12

from django.db import migrations, models


def approve_all(apps, schema_editor):
    Organisation = apps.get_model("organisations", "Organisation")
    Organisation.objects.all().update(approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_auto_20220818_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Approved'),
        ),
        migrations.RunPython(approve_all)
    ]
