# Generated by Django 2.2.24 on 2023-03-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_auto_20221102_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ['type'], 'verbose_name': 'Organization Type', 'verbose_name_plural': 'Organization Types'},
        ),
    ]
