# Generated by Django 3.2.25 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_alter_disease_symptoms'),
        ('organisations', '0012_alter_organisation_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='diseases',
            field=models.ManyToManyField(blank=True, to='diseases.Disease', verbose_name='Diseases'),
        ),
    ]
